// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/4/2026, 10:50:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/plugins/**/*.{js,ts,mjs}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/composables/**/*.{js,ts,mjs}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/utils/**/*.{js,ts,mjs}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/difusal/Documents/GitHub/turbo/testing/ongandessur-platform/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;